name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Debug information
        run: |
          export PYTHONPATH=/home/runner/work/SpellingTrainer/SpellingTrainer/app:$PYTHONPATH
          echo "Current directory: $(pwd)"
          echo "PYTHONPATH: $PYTHONPATH"
      
      - name: Test with unittest
        run: |
          python -m unittest


