VERSION = "1.0"

HIGH_PRIORITY_DICT_VERSION = 1
LOW_PRIORITY_DICT_VERSION = 1

# General
APP_NAME = 'Spelling Trainer'
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600

TITLE_FONT_SIZE = 30
FONT_SIZE = 16
HINT_FONT_SIZE = 10
HEADER_FONT_SIZE = 18
STATISTICS_FONT_SIZE = 26

TIMES_TO_SPELL_IF_CORRECT = 3
TIMES_TO_SPELL_IF_INCORRECT = 10

GREEN = "#6bbe66"
RED = "#ff4141"

# Mac OS
MACOS_VOICES = ['Daniel', 'Karen', 'Samantha', 'Moira', 'Tessa']
